////
:imagesdir: assets/images 
:includesdir: include
include::./{includesdir}/document_settings.adoc[]
////

== Current issues
The current PI Cluster version is still in the development phase. This means there are some issues. So before building the PI Cluster Frame, you may take a look at the current known issues. However the cluster frame itself is fully working. 

NOTE: Currently the PI Cluster frame (version: {current_version}) is at a point that it is useful. There are however some issues that needs to be addressed:

. The back-plane connectors doesn't align properly with the Raspberry PI
. The documentation is not fully completed yet or contains errors. 
. When using a PI4 it's difficult to remove the Ethernet cable.
. The rack-mount ears or not fully developed and tested.

:sectnums:

=== Back-plane alignment issue
In the development version *{development_version_beta}* the back-plane connectors don't align well with the PI Tray's connectors. Currently the Power connectors work. However the connectors which can be used for I2C are not tested, or operational. This misalignment makes placing the back-plane onto one PI Cluster Frame quite difficult, however it can be done. Once the back-plane is correctly aligned, both connectors should mate perfectly with the connectors on the PI Tray. However this is not tested with multiple PI Cluster frames stacked together. 

Severity: *HIGH* : Currently it is not advised to manufacture the PI Cluster back-plane PCB's until this issue is fixed or completely tested. 

*SOLVED* Issue is resolved in the current version *{current_version}* The alignment of the connectors is not perfect yet, but with the procedure explained in the  <<Attaching the back-plane>> section the alignment shouldn't be a problem. 

=== . The documentation is not fully completed yet or contains errors.
The documentation is becoming more and more complete, however it still needs a lot of work. At this point most of the assembly instructions should be complete. However the document itself is not tested fully, and may contain errors.

Severity: *HIGH* Documentation is required to be able to build the PI Cluster Frame. 

In the {current_version} all of the assembly steps are documented, however the documentation can (and properly will) contains errors, since it's not tested fully.

=== When using a PI4 it's difficult to remove the Ethernet cable
When a Pi4 is used in a Pi Tray the Ethernet port is on the right side instead of the left side. On the left side there is a small cut-out, so it's easier to remove a ethernet cable. However this cut-out is not available on the right side. Making it difficult to detach a ethernet cable.

Severity: *LOW*  This is just an inconvenience, and the front bezel needs a redesign anyway. 

=== The rack-mount ears or not fully developed and tested
The rackmount ears needs to be developped futher and to be tested. At this moment it's not recommended to place the cluster frame into a 19" rack.

:sectnums!:

