////
:includesdir: include
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
////
Hades <hades@spacebugs.nl>
v1.0, 2020-16-11

== Introduction
Having some Raspberry PI's at your disposal is already fun. Turning them into a cluster is really fun. Well.. at least I think it's fun. This project started when a few years back a friend and I came to the elusive idea of building a 10 node cluster. We had our reasons to do so. The first and most obvious reason is of course to have fun. The other reasons were about learning something about clusters, and software deployment on a cluster. 

At that time this friend got a 3D printer, and he started to design and print a frame which could hold 10 Pi's. One day he stopped by dropping off the frame for the 10 PI's. The idea was to link those 2 set's of 10 PI's together over a VPN, and we would have access to a 20 node cluster, in two separate geographic locations. How cool is that ?

We played around with it for a while, starting to configure the infrastructure needed to manage the cluster, and started to deploy software on the cluster. There was however one thing we needed to address. And that was the cooling of the cluster. Long story short: we find ourselves in busy day jobs, no time to spend on the cluster, and slowly the cluster, and the idea disappeared on a shelf. As it so often happens. 

Till recently. Due to some new challenges I needed an environment of a couple of physical hosts. Something that would scale.. A couple of PI's would do nicely.. In other words I needed a cluster. And yes I got one, but for the tasks I had in mind, I needed to fix the cooling issue. So I tried to alter the current frame. After several tries I discovered altering the original design would result in a complete redesign, or start from scratch. And of course there was the other option: Looking around if someone else already had developed a PI Cluster frame. 

And I did find some online, which looks promising, but the all have the same problems: 

- Most of the PI Cluster frames relay on PoE, which I don't want to use (don't have a PoE switch, with enough ports)
- Cooling issues, none of the Frames provides a integrated solution to provide prober cooling, other then using a PI HAT
- Some solutions didn't provide the modularity I'm after.

Looking at the current solutions available I started thinking about: 

- Creating a Cluster PI HAT, which would not only provide a way of cooling the PI node, but also provides power distribution.
- Another thing I likely need is to share a I2C bus between the nodes. This PI Cluster HAT could also take care of that.
- I also wanted some status LED's per node. Most likely RGB LED's so I could make 3x3 types of "signals" For example 'temp, cpu, power on'.
- And I really want a central power management module to power on/off nodes, which would 'remember' the power state of the nodes.

So basicity this means: Starting from scratch. However this was not something I wanted to do. And for good reasons: I needed a cluster quickly. Second, designing from scratch means a lot of work, and I already got a lot of projects on my hands. There was one thing however. I got this idea for really long time. And now I have the opportunity (I mean ultimate excuse) to realise this idea. This idea is about designing a backplane I could plug the PI's into. For some reason (and don't ask my why) a have fascination for backplanes. 

Long story short I started on the 5th of june 2020 to design a cluster frame that would: 

- Makes it possible to easy swap PI's
- Easy to maintain
- Relativity simple to build
- Hold 10 PI's in a 19" rack-able frame (But also should provide smaller cluster frames)
- Open Source, everyone should be able to build, alter, share this cluster frame.

Of course I had a lot of more requirements, but these were the essential ones.  During the development of this cluster frame I learned a lot. One of the things I needed to guard myself against was the phenomenon I like to call "feature creeps". Once I start designing it's oh so tempting to put in every possible thing that makes the project more feature rich, and of course all those features are "must haves". So right from the start I created a "requirements document". It's a few pages long, but in essence I could rewrite the whole document into one sentence:  

"Don't allow for any feature / aspect to slow the project down, or prevent it from coming up with a working proof of concept (PoC)".  

And even with such requirement document, it's hard to put great ideas about features aside.

But eventually I managed to just move forward, and even when somethings aren't perfect, or even won't work as intended I build a PoC in less then 3 months. Spending most of my evening and weekend to design and build this frame. 

The end result is that I designed 3 PCB's for the cluster frame: 

- PI Cluster HAT (Which provided, cooling and distribution of signals between the nodes)
- Power Board (Which is the "interface" which plugs into the backplane)
- LED Board (Which holds 3 RGB Led's)

All in all this design might require more parts to assemble and might be more complex then the other solutions out there. However It does exactly what I need, and makes maintaining and scaling a cluster of PI's really easy. And I hope it might be useful to someone else.